name: macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos-build-release:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Build Release
      run: swift build -c release
